---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_os::default]
    attributes:
      gusztavvargadr_workstations_os:
        requirements:
          locales:
            system: en-GB
            ui: en-GB
            user: en-GB
          datetime:
            timezone: GMT Standard Time
    verifier:
      inspec_tests:
        - test/smoke/default
