---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_svn::requirements]
      - recipe[gusztavvargadr_workstations_svn::tools]
      - recipe[gusztavvargadr_workstations_svn::profiles]
    attributes:
      gusztavvargadr_workstations_svn:
        profiles:
          workspaces:
            apache:
              address: http://svn.apache.org/repos
              directory: '/Users/vagrant/Repos/apache'
              repositories:
                asf/logging/log4net/trunk:
    verifier:
      inspec_tests:
        - test/smoke/default
