---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_vagrant::requirements]
      - recipe[gusztavvargadr_workstations_vagrant::tools]
      - recipe[gusztavvargadr_workstations_vagrant::profiles]
    attributes:
      gusztavvargadr_workstations_vagrant:
        profiles:
          plugins:
            vagrant-reload:
          boxes:
            https://atlas.hashicorp.com/ubuntu/boxes/trusty32:
    verifier:
      inspec_tests:
        - test/smoke/default
