---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_git::requirements]
      - recipe[gusztavvargadr_workstations_git::tools]
      - recipe[gusztavvargadr_workstations_git::profiles]
    attributes:
      gusztavvargadr_workstations_git:
        profiles:
          workspaces:
            github:
              address: https://github.com/github
              directory: '/Users/vagrant/Repos/github'
              repositories:
                gitignore:
    verifier:
      inspec_tests:
        - test/smoke/default
