---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_docker::default]
    attributes:
      gusztavvargadr_workstations_docker:
        profiles:
          public:
            images:
              microsoft/nanoserver:
    verifier:
      inspec_tests:
        - test/smoke/default
